### ISSUE TITLE
google place can we use 2 times in a same dom with different model name

### ISSUE THREAD

**Issue by dineshnadar** [israelidanny/ion-google-place#1]
hi,

This directive is awesome..

can we use 2 times in a same dom with different model name. can you please suggest on this how i can achieve this.

**Comment by matt-ward** [comment]
confirmed - dineshnadar fix solves issue of not being able to use directive multiple times in a single view. I was having this problem and modified the source with his fix and it works for me now.

**Comment by israelidanny** [comment]
implemented in a pull request! :)
