### ISSUE TITLE
Missing docs? not working 

### ISSUE THREAD

**Issue by stefanosc** [israelidanny/ion-google-place#20]
@israelidanny Thank you very much for this module.
I am writing because I am not able to get the directive to work.

At most I get an input box but when I type nothing happens.
Am I missing something?
I would appreciate any help.
@leandroz I know you got this to work some time ago.
Do you have any suggestion?

Thank you again

**Comment by israelidanny** [comment]
Have you included that required Google javascript files (as it says in
README)?

**Comment by lricoy** [comment]
Same happening here. I could check that the google object is sending the request but the popup is not rendered.

**Comment by lricoy** [comment]
I can even find it in the DOM, but It is not visible.
I can't find a way to change that behavior.

I am using the ionic beta.14

![image](https://cloud.githubusercontent.com/assets/2034367/5767248/affd6a80-9cee-11e4-9621-6cf941fbd435.png)

**Comment by lricoy** [comment]
@stefanosc , my problem was fixed by adding the .css file. 

@israelidanny maybe you could change the bower.json file to:

```
  "main": [
    "ion-google-place.js",
    "ion-google-place.css"
  ]
```

**Comment by stefanosc** [comment]
I just see now the notifications for this thread. Got busy with other projects and forgot to check again.
Thank you @israelidanny 
Good find @lricoy !

**Comment by israelidanny** [comment]
@stefanosc - glad you resolve it!
@lricoy - I did as you suggested :) thanks.
