### ISSUE TITLE
The popup input is not always focused

### ISSUE THREAD

**Issue by ivanst-stoyanov** [israelidanny/ion-google-place#22]
Sometimes when I click on the input that triggers the popup, the popup is shown, but the input is not focused and the keyboard does not show. It took me a while to understand why this is happening. The problem appears to be with the ionic auto scroll to focused input. Sometimes when the first (readonly) input is clicked and the popup is shown, ionic tries to scroll to the readonly input. 
I have tried to add a bigger delay to the code that focuses the input, but it is not working. I presume that there should be a way to stop the ionic auto scroll from triggering. 

Does any of you guys experienced this problem? Any fix for this?

P.P. I have created a forum post in the ionic forum regarding this issue. http://forum.ionicframework.com/t/disabling-ionic-auto-scroll-to-focused-input/16140

**Comment by ivanst-stoyanov** [comment]
I've solved the problem by focusing the input in a timeout with 0 delay and after that in a timeout with 50 delay.
 `$timeout(function () {
                                searchInputElement[0].focus();
}, 0);`

`$timeout(function () {
                                searchInputElement[0].focus();
                            }, 50);`

**Comment by stevecarlton** [comment]
@ivanst-stoyanov sounds like a good workaround as I am seeing this issue as well. May I ask where you added that code and are the two lines together?

**Comment by ivanst-stoyanov** [comment]
@stevecarlton I added the code inside ``` var onClick = function(e){```
You can add ```setTimeout(function(){
                                searchInputElement[0].focus();
                            },50);```
after the original timeout of 0

**Comment by stevecarlton** [comment]
Ahh, thank you for the clarification!
