### ISSUE TITLE
bower tag

### ISSUE THREAD

**Issue by izifortune** [israelidanny/ion-google-place#24]
Hi,
seems that you haven't tagged the lasted commit, from bower i can access only to the 0.0.1

**Comment by israelidanny** [comment]
Whoopsie :) I'll get to fixing it today.

**Comment by izifortune** [comment]
Thank you and congratulations for this really great widget

**Comment by Asfer80** [comment]
I'm still getting 0.0.1 from bower install ion-google-place.

And thanks for the great plugin :)

**Comment by fsbatista** [comment]
+1
