### ISSUE TITLE
The directive is does not work

### ISSUE THREAD

**Issue by softBarbarian** [israelidanny/ion-google-place#25]
I just tried to adding this directive to valilla ionic tabs project and here is waht i get:
![screen shot 2015-02-11 at 3 19 26 pm](https://cloud.githubusercontent.com/assets/1832398/6155435/6a8447d0-b201-11e4-8841-496ec7cce3fa.png)

Anybody can confirm this issue?

**Comment by israelidanny** [comment]
Have you included the css?

**Comment by israelidanny** [comment]
(And the google javascript files? See README.md)

**Comment by softBarbarian** [comment]
got it! thanks 
Keep up the good work

**Comment by israelidanny** [comment]
you're welcome :) glad you're liking the work
