### ISSUE TITLE
geocoder

### ISSUE THREAD

**Issue by izifortune** [israelidanny/ion-google-place#26]
A quick question, 
isn't better to instance a new geocoder when we actually need it?
Because what if my smartphone don't have network at the moment that i launch the app?

So do you think its better to call when we actually need it? ( and also make it conditionally? )

**Comment by israelidanny** [comment]
Interesting edge case, could be a good idea.

You mean injecting a script tag?

**Comment by izifortune** [comment]
Yeah exactly, i mean its a possibility with smartphones
