### ISSUE TITLE
Bower package is outdated

### ISSUE THREAD

**Issue by ahaverty** [israelidanny/ion-google-place#83]
I'm new enough to Ionic/Bower, but I believe the package is outdated (v0.0.1).
I thought by grabbing the github url with bower, that I was pulling the latest, but I believe bower actually looks for the latest 'release'? (Which is v0.0.1)
Workaround was to bower the latest commit.
Thank you.

**Comment by rodriguezmanu** [comment]
"dependencies": {
 "ion-google-place": "https://github.com/israelidanny/ion-google-place.git#3a9a818656987af7bdc631c660dc4d6b5779a1e3"
   }

**Comment by vitaliy-bobrov** [comment]
But why not to create a new release for bower?

**Comment by ahaverty** [comment]
It doesn't look like this repo is being maintained anymore (Currently 18PRs) @vitaliy-bobrov, but that would be the solution if it was! I'm no longer using this repo, but perhaps there's a fork being maintained by someone else.
(Github could do with some kind of voting system for assigning new contributors to neglected projects, its a shame to waste @israelidanny's good work.. But also understandable 😕)

**Comment by israelidanny** [comment]
If there's a list of stuff that would be valuable to merge, I'd gladly do it.

**Comment by ahaverty** [comment]
Appreciate the response @israelidanny and the great repo. I'm personally not using it anymore though so I won't be much help, but best of luck all!

**Comment by israelidanny** [comment]
I'll probably take some time within the next few days to go over the repo's issues & merge / improve on the code.
